logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 192.168.100.102
    port: 5672
    virtual-host: /rabbitmq-learn
    password: 123456
    username: rabitmq-learn
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: none #none manual auto
        retry:
          enabled: true # 消费者失败重试
          initial-interval: 1000ms #初始失败等待时长
          multiplier: 1 #下次失败的等待时长倍数，下次等待市场 = m * l
          max-attempts: 3 #最大重试次数
          stateless: true # true无状态，false有状态。如果业务中包含事务，这里为false